packages:
  - examples/**
  - packages/**
  - '!**/test/**'
catalog:
  vite: '>=5.0.0'
onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@nestjs/core'
  - '@swc/core'
  - esbuild
  - unrs-resolver
